#ifndef __CORELIB_INTERNAL_BUILD_TYPE_H__
#define __CORELIB_INTERNAL_BUILD_TYPE_H__ 1

#if defined(CMAKE_BUILD_TYPE_DEBUG)
#define CORELIB_BUILD_TYPE "Debug"
#define CORELIB_BUILD_TYPE_DEBUG 1
#define CORELIB_DEBUG 1
#elif defined(CMAKE_BUILD_TYPE_RELEASE)
#define CORELIB_BUILD_TYPE "Release"
#define CORELIB_BUILD_TYPE_RELEASE 1
#define CORELIB_RELEASE 1
#elif defined(CMAKE_BUILD_TYPE_RELWITHDEBINFO)
#define CORELIB_BUILD_TYPE "RelWithDebInfo"
#define CORELIB_BUILD_TYPE_RELWITHDEBINFO 1
#define CORELIB_RELWITHDEBINFO 1
#define CORELIB_RELEASE 1
#define CORELIB_DEBUG 1
#elif defined(CMAKE_BUILD_TYPE_MINSIZEREL)
#define CORELIB_BUILD_TYPE "MinSizeRel"
#define CORELIB_BUILD_TYPE_MINSIZEREL 1
#define CORELIB_MINSIZEREL 1
#define CORELIB_RELEASE 1
#else
#error "Unknown build type"
#endif

#ifndef CORELIB_BUILD_TYPE
#error "CORELIB_BUILD_TYPE is not defined"
#endif

#ifndef CORELIB_BUILD_TYPE_DEBUG
#define CORELIB_BUILD_TYPE_DEBUG 0
#endif

#ifndef CORELIB_DEBUG
#define CORELIB_DEBUG 0
#endif

#ifndef CORELIB_BUILD_TYPE_RELEASE
#define CORELIB_BUILD_TYPE_RELEASE 0
#endif

#ifndef CORELIB_RELEASE
#define CORELIB_RELEASE 0
#endif

#ifndef CORELIB_BUILD_TYPE_RELWITHDEBINFO
#define CORELIB_BUILD_TYPE_RELWITHDEBINFO 0
#endif

#ifndef CORELIB_RELWITHDEBINFO
#define CORELIB_RELWITHDEBINFO 0
#endif

#ifndef CORELIB_BUILD_TYPE_MINSIZEREL
#define CORELIB_BUILD_TYPE_MINSIZEREL 0
#endif

#ifndef CORELIB_MINSIZEREL
#define CORELIB_MINSIZEREL 0
#endif

#endif // __CORELIB_INTERNAL_BUILD_TYPE_H__
