function(set_build_type_defines target)
	if (NOT TARGET ${target})
        	message(FATAL_ERROR "Target '${target}' does not exist.")
	endif()

	if(CMAKE_CONFIGURATION_TYPES)
		foreach(config ${CMAKE_CONFIGURATION_TYPES})
			if(config STREQUAL "Debug")
				target_compile_definitions(${target} PUBLIC __DEBUG__)
			elseif(config STREQUAL "Release")
				target_compile_definitions(${target} PUBLIC __RELEASE__)
			elseif(config STREQUAL "RelWithDebInfo")
				target_compile_definitions(${target} PUBLIC __REL_WITH_DEB_INFO__)
			elseif(config STREQUAL "MinSizeRel")
				target_compile_definitions(${target} PUBLIC __MIN_SIZE_REL__)
			endif()
		endforeach()
	else()
		if(CMAKE_BUILD_TYPE STREQUAL "Debug")
			target_compile_definitions(${target} PUBLIC __DEBUG__)
		elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
			target_compile_definitions(${target} PUBLIC __RELEASE__)
		elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
			target_compile_definitions(${target} PUBLIC __REL_WITH_DEB_INFO__)
		elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
			target_compile_definitions(${target} PUBLIC __MIN_SIZE_REL__)
		else()
			message(NOTICE "CMAKE_BUILD_TYPE is not set to a valid value. Defaulting to 'Debug'.")
			set(CMAKE_BUILD_TYPE "Debug")
			target_compile_definitions(${target} PUBLIC __DEBUG__)
		endif()
	endif()
endfunction()
