function(set_build_type_defines target)
	if (NOT TARGET ${target})
        	message(FATAL_ERROR "Target '${target}' does not exist.")
	endif()

	if(CMAKE_CONFIGURATION_TYPES)
		foreach(config ${CMAKE_CONFIGURATION_TYPES})
			if(config STREQUAL "Debug")
				target_compile_definitions(${target} PUBLIC DEBUG)
			elseif(config STREQUAL "Release")
				target_compile_definitions(${target} PUBLIC RELEASE)
			elseif(config STREQUAL "RelWithDebInfo")
				target_compile_definitions(${target} PUBLIC REL_WITH_DEB_INFO)
			elseif(config STREQUAL "MinSizeRel")
				target_compile_definitions(${target} PUBLIC MIN_SIZE_REL)
			endif()
		endforeach()
	else()
		if(CMAKE_BUILD_TYPE STREQUAL "Debug")
			target_compile_definitions(${target} PUBLIC DEBUG)
		elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
			target_compile_definitions(${target} PUBLIC RELEASE)
		elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
			target_compile_definitions(${target} PUBLIC REL_WITH_DEB_INFO)
		elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
			target_compile_definitions(${target} PUBLIC MIN_SIZE_REL)
		else()
			message(NOTICE "CMAKE_BUILD_TYPE is not set to a valid value. Defaulting to 'Debug'.")
			set(CMAKE_BUILD_TYPE "Debug")
			target_compile_definitions(${target} PUBLIC DEBUG)
		endif()
	endif()
endfunction()
