function(set_build_type_defines target)
	if (NOT TARGET ${target})
        	message(FATAL_ERROR "Target '${target}' does not exist.")
	endif()

	if(CMAKE_CONFIGURATION_TYPES)
		foreach(config ${CMAKE_CONFIGURATION_TYPES})
			if(config STREQUAL "Debug")
				target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_DEBUG)
			elseif(config STREQUAL "Release")
				target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_RELEASE)
			elseif(config STREQUAL "RelWithDebInfo")
				target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_RELWITHDEBINFO)
			elseif(config STREQUAL "MinSizeRel")
				target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_MINSIZEREL)
			endif()
		endforeach()
	else()
		if(CMAKE_BUILD_TYPE STREQUAL "Debug")
			target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_DEBUG)
		elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
			target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_RELEASE)
		elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
			target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_RELWITHDEBINFO)
		elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
			target_compile_definitions(${target} PUBLIC CMAKE_BUILD_TYPE_MINSIZEREL)
		else()
			message(FATAL_ERROR "Unsupported build type: ${CMAKE_BUILD_TYPE}")
		endif()
	endif()
endfunction()
